### ISSUE TITLE
Fixbb error

### ISSUE THREAD

**Issue by shounakb20** [schenc3/InteractiveROSETTA#12]
Generated during the fixbb protocol

Here is the log:

Daemon completed scoring job
 Selector-Error: invalid model "designed_view".
Traceback (most recent call last):
  File "/home/shounak/Downloads/InteractiveROSETTA_2.2_Linux/scripts/fixbb.py", line 366, in gridClick
    self.desMenuSelect(event)
  File "/home/shounak/Downloads/InteractiveROSETTA_2.2_Linux/scripts/fixbb.py", line 1147, in desMenuSelect
    self.cmd.select("dessele", "resi " + seqpos + " and model " + firstmodel + " and chain " + chain)
  File "/usr/lib/python2.7/dist-packages/pymol/selecting.py", line 118, in select
    if _self._raising(r,_self): raise pymol.CmdException  
pymol.CmdException:  Error: None

**Comment by walcob** [comment]
InteractiveROSETTA Session Log

Operating System: Linux - Ubuntu 14.04 trusty  Release: 3.13.0-79-generic
Processor: x86_64
Architecture: 64bit ELF 
Python Version: 2.7.6

Clicked the change scorefxn button
Cancelled change scorefxn operation
Attempting to fetch PDB 2b3p from RCSB
... PDB loading removed ...
Colored residues by SS
Colored residues by B-factor
Colored residues by HMMSTR
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
Go button clicked
Changed protocol to Point Mutations
New model selected: 2b3p
Attempted to calculate scores for this model
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
Scoring input uploaded locally at scoreinput
Position A:L195 was selected
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
Go button clicked
Changed protocol to Protein Design (Fixbb)
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
Design view menu was set to 1: L195
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
Added CYS to palette
Apply selection button clicked
Design button clicked
Wrote a resfile to fixbb.resfile
Design input uploaded locally at designinput
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
Design view menu was set to 1: L195
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 191 to 2b3p|A position 191
New Selection Entry: 
Selected 2b3p|A position 1 to 2b3p|A position 556
Selected all atoms
Turned cartoon display on
New Selection Entry: 
Selected 2b3p|A position 1 to 2b3p|A position 556
New Selection Entry: 
Selected 2b3p|A position 1 to 2b3p|A position 556
New Selection Entry: 
Selected 2b3p|A position 1 to 2b3p|A position 556
New Selection Entry: 
Selected 2b3p|A position 1 to 2b3p|A position 556
New Selection Entry: 
Selected 2b3p|A position 1 to 2b3p|A position 556
New Selection Entry: 
Selected 2b3p|A position 1 to 2b3p|A position 556
New Selection Entry: 
Selected 2b3p|A position 1 to 2b3p|A position 556
New Selection Entry: 
Selected 2b3p|A position 1 to 2b3p|A position 556
New Selection Entry: 
Selected 2b3p|A position 54 to 2b3p|A position 54
New Selection Entry: 
Selected 2b3p|A position 54 to 2b3p|A position 54
New Selection Entry: 
Selected 2b3p|A position 54 to 2b3p|A position 54
New Selection Entry: 
Selected 2b3p|A position 54 to 2b3p|A position 54
New Selection Entry: 
Selected 2b3p|A position 54 to 2b3p|A position 54
New Selection Entry: 
Selected 2b3p|A position 54 to 2b3p|A position 54
New Selection Entry: 
Selected 2b3p|A position 54 to 2b3p|A position 54
New Selection Entry: 
Selected 2b3p|A position 54 to 2b3p|A position 54
New Selection Entry: 
Selected 2b3p|A position 54 to 2b3p|A position 54
New Selection Entry: 
Selected 2b3p|A position 54 to 2b3p|A position 54
sessionlog
Displaying sessionlog.`
